name: Slack Notification on Failure

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  example-job:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: |
          echo "This is an example step."
          exit 1 # This will cause the step to fail

      - name: Slack Notification
        if: failure() # This step will run only if the previous step fails
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: |
            *Repository*: ${{ github.repository }}
            *Workflow Run*: ${{ github.workflow }}
            *Branch*: ${{ github.ref }}
            *Commit*: ${{ github.sha }}
            *Actor*: ${{ github.actor }}
            *Failed Job*: ${{ github.job }}
            *Details*: 
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>
          SLACK_TITLE: '[${{ github.repository }}] Run failed: ${{ github.workflow }} - ${{ github.ref_name }} (${{ github.sha }})'

