name: Slack Notification on Failure

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  example-job:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: |
          echo "This is an example step."
          exit 1 # This will cause the step to fail

      - name: Slack Notification
        if: failure() # This step will run only if the previous step fails
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: |
            *Repository*: ${{ github.repository }}
            *Event Name*: ${{ github.event_name }}
            *Branch*: ${{ github.ref }}
            *Commit Message*: ${{ github.event.head_commit.message }}
            *Actor*: ${{ github.actor }}
            *Workflow*: ${{ github.workflow }}
            *Job Name*: ${{ github.job }}
            *Run Number*: ${{ github.run_number }}
            *Run ID*: ${{ github.run_id }}
            *Failed Step*: 'Example Step' # Adjust based on your workflow
          SLACK_TITLE: 'GitHub Action Failed'

