name: Slack Notification on Failure

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  example-job:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: |
          echo "This is an example step."
          exit 1 # This will cause the step to fail

      - name: Slack Notification
        if: failure() # This step will run only if the previous step fails
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: 'The GitHub Action has failed!'
          SLACK_TITLE: 'Failure Notification'
